backend:
    name: git-gateway
    branch: main

local_backend: true

media_folder: '_site/assets/uploads'
public_folder: '/assets/uploads'

collections:
    - name: 'events'
      label: 'Events'
      folder: 'src/events'
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      editor:
          preview: false
      create: true
      fields:
          # - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'event' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - { label: 'Date & Time', name: 'datetime', widget: 'datetime' }
          - { label: 'Location', name: 'location', widget: 'string' }
          - { label: 'Booking Link', name: 'booking', widget: 'string' }
          - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
